/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErasRouteImport } from './routes/eras'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FiguresIndexRouteImport } from './routes/figures.index'
import { Route as FiguresSlugRouteImport } from './routes/figures.$slug'

const ErasRoute = ErasRouteImport.update({
  id: '/eras',
  path: '/eras',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresIndexRoute = FiguresIndexRouteImport.update({
  id: '/figures/',
  path: '/figures/',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresSlugRoute = FiguresSlugRouteImport.update({
  id: '/figures/$slug',
  path: '/figures/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/eras': typeof ErasRoute
  '/figures/$slug': typeof FiguresSlugRoute
  '/figures/': typeof FiguresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/eras': typeof ErasRoute
  '/figures/$slug': typeof FiguresSlugRoute
  '/figures': typeof FiguresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/eras': typeof ErasRoute
  '/figures/$slug': typeof FiguresSlugRoute
  '/figures/': typeof FiguresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/eras' | '/figures/$slug' | '/figures/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/eras' | '/figures/$slug' | '/figures'
  id: '__root__' | '/' | '/about' | '/eras' | '/figures/$slug' | '/figures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ErasRoute: typeof ErasRoute
  FiguresSlugRoute: typeof FiguresSlugRoute
  FiguresIndexRoute: typeof FiguresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/eras': {
      id: '/eras'
      path: '/eras'
      fullPath: '/eras'
      preLoaderRoute: typeof ErasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures/': {
      id: '/figures/'
      path: '/figures'
      fullPath: '/figures/'
      preLoaderRoute: typeof FiguresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures/$slug': {
      id: '/figures/$slug'
      path: '/figures/$slug'
      fullPath: '/figures/$slug'
      preLoaderRoute: typeof FiguresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ErasRoute: ErasRoute,
  FiguresSlugRoute: FiguresSlugRoute,
  FiguresIndexRoute: FiguresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
